"""
REBUILD — APPENDIX V3 WORD RENDERING
Renders outputs/rebuild/appendix_v3/table_{1..14}.csv into a single Word
document for the dissertation appendix. Pure rendering: no numbers computed
here; the CSVs (asserted by Stage 8) are the source of truth.
Output: outputs/rebuild/APPENDIX_V3_TABLES.docx
"""
import sys
import pandas as pd
from pathlib import Path
from docx import Document
from docx.shared import Pt

sys.stdout.reconfigure(encoding='utf-8', errors='replace')

TITLES = {
    1: 'Summary Statistics (CRSP Sample)',
    2: 'Mean 30-Day CAR by Subgroup, with Welch Difference Tests',
    3: 'Main Regression: 30-Day CAR on Hypothesis Variables and Controls (HC3)',
    4: 'Sample Restrictions (Timing, FCC, and ROA Coefficients)',
    5: 'Standard-Error Methods',
    6: 'Timing Coefficient by Firm-Size Quartile',
    7: 'FCC Coefficient by Firm-Size Quartile (Treated Counts Shown)',
    8: 'Specification Robustness (Year Fixed Effects)',
    9: 'Alternative Explanations (Breach Severity)',
    10: 'Factor-Model Controls (FF3)',
    11: 'Abnormal Log Turnover (Event [-5,+25] vs Estimation [-240,-60])',
    12: 'Random-Forest Feature Importance',
    13: 'Pre-Announcement Abnormal Returns (Leakage Windows)',
    14: 'Equivalence Testing (TOST, Pre-Specified ±2.10pp Bound)',
}

doc = Document()
doc.add_heading('Essay 1 Appendix — Canonical V3 Tables', level=1)
p = doc.add_paragraph('All values regenerate from run_all.py (Canonical V3 chain, scripts 150–159) '
                      'and assert against outputs/rebuild/constants_v3.json. Generated by scripts/160.')
p.runs[0].font.size = Pt(9)

for i in range(1, 15):
    df = pd.read_csv(f'outputs/rebuild/appendix_v3/table_{i}.csv').fillna('')
    doc.add_heading(f'Table {i}. {TITLES[i]}', level=2)
    t = doc.add_table(rows=len(df) + 1, cols=len(df.columns))
    t.style = 'Light Grid Accent 1'
    for j, c in enumerate(df.columns):
        t.rows[0].cells[j].text = str(c)
    for r, (_, row) in enumerate(df.iterrows(), start=1):
        for j, v in enumerate(row):
            t.rows[r].cells[j].text = str(v)
    for row in t.rows:
        for cell in row.cells:
            for par in cell.paragraphs:
                for run in par.runs:
                    run.font.size = Pt(8)

out = Path('outputs/rebuild/APPENDIX_V3_TABLES.docx')
doc.save(out)
print(f'Saved: {out}')
