"""ESSAY 1: sample attrition ledger, computed live from the v3 chain.

Part K of the Run-All Follow-Up (2026-09-29). Every step from the 1,054 PRC notification
records to the Essay 1 regression sample, with the drop count and the reason at each
step, and the treated count at three levels - events, organisations, parent CIKs.

Reads only committed v3 chain artefacts:
    Data/processed/rebuild/stage2_signed.csv   (1,054 notification records, Gate 1 verdicts)
    Data/processed/rebuild/stage3_events.csv   (firm-day events after CIK+date dedup)
    Data/processed/rebuild/CANONICAL_V3.csv    (events after Gate 2, with covariates)
It does NOT read the pre-rebuild FINAL_DISSERTATION_DATASET*, and it does not recompute
anything: the sample definition is lifted verbatim from scripts/156.

Every step is asserted to close arithmetically: retained + dropped == input.

THE LEDGER IS WRITTEN BEFORE THE FINAL CHECK. The last thing this script does is compare
the recomputed N and treated count against outputs/rebuild/constants_v3.json and exit
nonzero if they differ, so the file exists on disk whether or not the check passes.
"""
import json
import sys
from pathlib import Path

import pandas as pd

REBUILD = Path('Data/processed/rebuild')
LEDGER = Path('outputs/ESSAY1_SAMPLE_ATTRITION_LEDGER_V3.md')
CONSTANTS = Path('outputs/rebuild/constants_v3.json')

# The Essay 1 regression sample, verbatim from scripts/156:
#     reg = ev[ev['has_crsp_data'] == 1].dropna(subset=CONTROLS)
CONTROLS = ['fcc_form499', 'immediate_disclosure', 'prior_breaches_1yr', 'health_breach',
            'firm_size_log', 'leverage', 'roa', 'car_30d']

L = []
N_ASSERTS = [0]


def log(m=''):
    print(m)
    L.append(str(m))


def A(desc, cond, detail=''):
    N_ASSERTS[0] += 1
    if not cond:
        raise AssertionError('%s%s' % (desc, (' [%s]' % detail) if detail else ''))


def levels(d, treated_only=True):
    """(events, organisations, parent CIKs) for the treated rows of d."""
    x = d[d['fcc_form499'] == 1] if treated_only else d
    return len(x), x['org_name'].nunique(), x['final_cik'].nunique()


s2 = pd.read_csv(REBUILD / 'stage2_signed.csv', low_memory=False)
s3 = pd.read_csv(REBUILD / 'stage3_events.csv', low_memory=False)
ev = pd.read_csv(REBUILD / 'CANONICAL_V3.csv', low_memory=False)

log('# Essay 1 — sample attrition ledger (v3, computed live)')
log()
log('Generated by `scripts/247_essay1_ledger_attrition_v3.py` from today\'s committed v3')
log('chain. Nothing here is copied from a constants file; the figures below are what the')
log('chain contains now. The final check compares them to `constants_v3.json`.')
log()

# ---------------------------------------------------------------- the chain
rows = []


def step(name, n_in, n_out, reason):
    dropped = n_in - n_out
    A('%s closes arithmetically' % name, n_out + dropped == n_in,
      'in %d, out %d, dropped %d' % (n_in, n_out, dropped))
    rows.append((name, n_in, dropped, n_out, reason))
    return n_out


n0 = len(s2)
A('universe is 1,054 notification records', n0 == 1054, str(n0))

n1 = int(s2['final_cik'].notna().sum())
step('Gate 1 — entity resolution', n0, n1,
     'No parent CIK could be assigned to the notifying organisation (private, foreign, '
     'dissolved, or not resolvable to an SEC registrant).')

n2 = len(s3)
step('Stage 3 — firm-day deduplication', n1, n2,
     'Multiple notification records for the same parent CIK on the same breach date are '
     'one firm-day event.')

n3 = len(ev)
step('Gate 2 — rolling-campaign rule', n2, n3,
     'Events chained to an earlier event for the same parent within the campaign window '
     'are folded into that event.')

crsp = ev[ev['has_crsp_data'] == 1]
n4 = len(crsp)
step('Stage 5 — security link to CRSP', n3, n4,
     'No CRSP security could be linked at the breach date, so no car_30d exists '
     '(private registrant, no US-listed equity at the date, or absent from the '
     'committed WRDS extract).')

reg = crsp.dropna(subset=CONTROLS)
n5 = len(reg)
step('Stage 6 — complete covariates', n4, n5,
     'At least one of the eight regression variables is missing.')

log('## The chain')
log()
log('| Step | In | Dropped | Out | Why the drop |')
log('|---|---:|---:|---:|---|')
for name, i, d, o, why in rows:
    log('| %s | %d | %d | **%d** | %s |' % (name, i, d, o, why))
log()
log('Each row is asserted to close: out + dropped == in. %d assertions so far.'
    % N_ASSERTS[0])
log()

# ---------------------------------------------------------------- the last step in detail
log('## The covariate drop, variable by variable')
log()
log('Counted over the %d events with CRSP data. A single event can be missing more than' % n4)
log('one variable, so these do not sum to the %d dropped.' % (n4 - n5))
log()
log('| Variable | Missing |')
log('|---|---:|')
for c in CONTROLS:
    log('| `%s` | %d |' % (c, int(crsp[c].isna().sum())))
log()
miss_any = int(crsp[CONTROLS].isna().any(axis=1).sum())
A('the any-missing count equals the drop', miss_any == n4 - n5,
  'any-missing %d, dropped %d' % (miss_any, n4 - n5))
log('Events missing at least one variable: **%d**, which is exactly the drop.' % miss_any)
log()

# ---------------------------------------------------------------- treated, three levels
log('## Treated counts at each level')
log()
log('"Organisations" counts distinct `org_name`; "parent CIKs" counts distinct')
log('`final_cik`. One parent CIK can cover several organisations (a filer and its')
log('subsidiaries), which is why the two differ.')
log()
log('| Stage | Treated events | Treated organisations | Treated parent CIKs |')
log('|---|---:|---:|---:|')
for label, frame in (('After Gate 2 (all events)', ev),
                     ('With CRSP data', crsp),
                     ('Essay 1 regression sample', reg)):
    e, o, c = levels(frame)
    log('| %s | %d | %d | %d |' % (label, e, o, c))
log()
te, to, tc = levels(reg)
A('treated events do not exceed the sample', te <= n5, '%d of %d' % (te, n5))
A('organisations do not exceed treated events', to <= te, '%d vs %d' % (to, te))
A('parent CIKs do not exceed organisations', tc <= to, '%d vs %d' % (tc, to))

log('## Totals')
log()
log('| | Count |')
log('|---|---:|')
log('| Essay 1 regression sample (N) | **%d** |' % n5)
log('| Treated events in it | **%d** |' % te)
log('| Treated organisations | %d |' % to)
log('| Treated parent CIKs | %d |' % tc)
log('| Control events | %d |' % (n5 - te))
log()

# ---------------------------------------------------------------- write BEFORE the check
c_json = json.loads(CONSTANTS.read_text(encoding='utf-8'))
committed_n = c_json.get('N_regression')
committed_t = c_json.get('treated_regression')

log('## Against `constants_v3.json`')
log()
log('| Quantity | Recomputed here | Committed in `constants_v3.json` | Agree |')
log('|---|---:|---:|---|')
log('| Regression sample N | %d | %s | %s |'
    % (n5, committed_n, 'yes' if n5 == committed_n else '**NO**'))
log('| Treated events | %d | %s | %s |'
    % (te, committed_t, 'yes' if te == committed_t else '**NO**'))
log()

mismatch = (n5 != committed_n) or (te != committed_t)
if mismatch:
    log('**PENDING REBASELINE: constants_v3.json is stale against CANONICAL_V3.**')
    log()
    log('`constants_v3.json` is written by `scripts/158`, which has not been re-run since')
    log('the chain last changed. Nothing above is wrong: the ledger describes the data as')
    log('it stands, and the constants file describes the data as it stood when 158 last')
    log('ran. Until 158 is re-run, cite the ledger for the chain and treat the committed')
    log('N and treated counts as superseded.')
else:
    log('The ledger and the committed constants agree.')
log()
log('---')
log()
log('Assertions passed: %d.' % N_ASSERTS[0])

LEDGER.parent.mkdir(parents=True, exist_ok=True)
LEDGER.write_text('\n'.join(L) + '\n', encoding='utf-8')
print()
print('Written: %s (%d assertions passed)' % (LEDGER, N_ASSERTS[0]))

if mismatch:
    print()
    print('  regression sample N : recomputed %d | constants_v3.json %s' % (n5, committed_n))
    print('  treated events      : recomputed %d | constants_v3.json %s' % (te, committed_t))
    print()
    print('PENDING REBASELINE: constants_v3.json is stale against CANONICAL_V3.')
    sys.exit(1)

print('constants_v3.json agrees with CANONICAL_V3.')
